### ISSUE TITLE
npm run serve错误，请问是否需要其他配置？

### ISSUE THREAD

**Issue by nobodxbodon** [mandolin/hia-multilingual-vue-template#1]
git clone 下来之后，只运行了`$ npm install`

```
$ npm run serve

> hia-multilingual-vue-template@1.0.0 serve /Users/xuanwu/git/hia-multilingual-vue-template
> vue-cli-service serve

 INFO  Starting development server...
(node:3996) ExperimentalWarning: The WHATWG Encoding Standard implementation is an experimental API. It should not yet be used in production applications.
98% after emitting CopyPlugin

 ERROR  Failed to compile with 3 errors                                   上午9:43:15

 error  in ./src/App.vue?vue&type=template&id=7ba5bd90&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: /Users/xuanwu/git/hia-multilingual-vue-template/src/App.vue:2:1
    1| 
  > 2| #应用
-------^
    3|     .主容器.mha.w600
    4|         router-view
    5|         .分隔线: hr

"应用
" is not a valid ID.
    at makeError (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-er
ror/index.js:32:13)
    at Lexer.error (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-
lexer/index.js:59:15)
    at Lexer.id (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lex
er/index.js:428:12)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_
modules/pug-lexer/index.js:1460:23)
    at Lexer.advance (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1494:15)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1460:23)
    at Lexer.getTokens (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1516:12)
    at lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:100:27)
    at Function.loadString [as string] (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-load/index.js:44:24)
    at compileBody (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:242:16)
    at Object.module.exports (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-plain-loader/index.js:11:24)

 @ ./src/App.vue?vue&type=template&id=7ba5bd90&lang=pug& 1:0-447 1:0-447
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.50.103:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/views/About.vue?vue&type=template&id=039c5b43&scoped=true&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: /Users/xuanwu/git/hia-multilingual-vue-template/src/views/About.vue:2:1
    1| 
  > 2| .介绍(主题=春天)
-------^
    3|     //- note 建议（仅供参考）：使用英文样式类和英文属性来：呈现基本样式、与api相关或api对其有命名约束的相关行为的标识
    4|     //- note 建议（仅供参考）：使用中文属性来：表达语义、呈现站点/频道/页面等（偏于相对统一的）通用样式、与相对纯粹的业务相关的行为的标识
    5|     #介绍.着重文字.mha(介绍文字 主题='春天') 这是一个春天的主题

"介绍" is not a valid class name.  Class names can only contain "_", "-", a-z and 0-9, and must contain at least one of "_", or a-z
    at makeError (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:59:15)
    at Lexer.className (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:448:12)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1460:23)
    at Lexer.advance (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1496:15)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1460:23)
    at Lexer.getTokens (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1516:12)
    at lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:100:27)
    at Function.loadString [as string] (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-load/index.js:44:24)
    at compileBody (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:242:16)
    at Object.module.exports (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-plain-loader/index.js:11:24)

 @ ./src/views/About.vue?vue&type=template&id=039c5b43&scoped=true&lang=pug& 1:0-476 1:0-476
 @ ./src/views/About.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.50.103:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/views/Home.vue?vue&type=template&id=fae5bece&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: /Users/xuanwu/git/hia-multilingual-vue-template/src/views/Home.vue:2:1
    1| 
  > 2| .主页
-------^
    3|     img(alt='Vue 徽标' src="../assets/logo.png")
    4|     p 本次操作时间: {{本次操作时间}}
    5|     button(@click = '更新一些时间') 更新(@click = '更新一些时间'无效)

"主页
" is not a valid class name.  Class names can only contain "_", "-", a-z and 0-9, and must contain at least one of "_", or a-z
    at makeError (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-error/index.js:32:13)
    at Lexer.error (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:59:15)
    at Lexer.className (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:448:12)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1460:23)
    at Lexer.advance (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1496:15)
    at Lexer.callLexerFunction (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1460:23)
    at Lexer.getTokens (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:1516:12)
    at lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-lexer/index.js:12:42)
    at Object.lex (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:100:27)
    at Function.loadString [as string] (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-load/index.js:44:24)
    at compileBody (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug/lib/index.js:242:16)
    at Object.module.exports (/Users/xuanwu/git/hia-multilingual-vue-template/node_modules/pug-plain-loader/index.js:11:24)

 @ ./src/views/Home.vue?vue&type=template&id=fae5bece&lang=pug& 1:0-463 1:0-463
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.50.103:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by mandolin** [comment]
安装后需要覆盖一下 pug-lexer/index.js 。
readme已更新。

**Comment by nobodxbodon** [comment]
覆盖后，运行 serve成功。网页显示如下，确认一下是否如预期？
![Screen Shot 2020-01-01 at 3 53 19 PM](https://user-images.githubusercontent.com/392497/71647655-0ac80100-2caf-11ea-9f8f-1bc216e0a527.png)

**Comment by mandolin** [comment]
正常了

**Comment by nobodxbodon** [comment]
多谢。
